---
name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Hello:
    runs-on: ubuntu-18.04
    steps:
      - name: Hello World!
        run: echo "Hello World"
        
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.17'

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
          golangci-lint run          
#jobs:

#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2

#    - name: Set up Go
#      uses: actions/setup-go@v2
#      with:
#        go-version: 1.17

#    - name: Build
#      run: go build -v ./...

#    - name: Test
#      run: go test -v ./...

#jobs:
#  test:
#    runs-on: ubuntu-latest
#    container: lesovsky/pgcenter-testing:v0.0.1
